[Tests] Add cypress e2e test for deleting added city
bartius-dev/weather-comparitor pull request #68
Opened 2020-12-03 08:34 UTC by dpakach

Add cypress End-To-End tests for:

1. Delete a city from the weather table.

2. Add multiple cities and delete them one by one.

2020-12-03 08:39 UTC, Talank commented on cypress/integration/deleteCity.spec.js
> +                .click()
can you make a custom command for performing this task!

2020-12-03 08:56 UTC, Talank approved these changes
LGTM :+1:

2020-12-08 02:59 UTC, bartius-nigel requested changes
This looks great, thank you for catching some great issues!

2020-12-08 02:59 UTC, bartius-nigel commented on cypress/fixtures/cityCountry.json
> -  "2": {
awesome.

2020-12-08 02:59 UTC, bartius-nigel commented on cypress/integration/searchCity.spec.js
> +            cy.get('.name-name-cell').should('be.visible')
id prefer this to stay as '.city-name-cell' if thats possible.

2020-12-08 02:59 UTC, bartius-nigel commented on cypress/support/commands.js
> -Cypress.Commands.add('searchForCity', (city, country) => {
Same here, id prefer this to stay as 'city'

2020-12-09 14:41 UTC, dpakach commented
@bartius-nigel, sorry was busy yesterday, but I've fixed all the issues. Please have a look

2020-12-12 18:30 UTC, bartius-dev approved these changes

2020-12-12 18:31 UTC, merged